name: Android Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK and Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: temurin   # obligatoire
          java-version: 21
          cache: maven

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: "-no-window -no-audio"
          script: |
            echo "Emulator started"

      - name: Run tests Android
        run: mvn clean test -Duat.currentEnv=android "
