name: Android Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          nohup appium --port 4723 --log-level info &
          sleep 5
          appium driver install uiautomator2
     - name: List all files recursively
            run: |
              echo "Listing all files in the project:"
              ls -R
      - name: Run Android Emulator and Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-port: 5556
          target: default
          arch: x86_64
          profile: pixel_6
          script: |
            adb devices
            mvn clean test -Dspring.config.location=src/test/resources/application.yaml -Duat.currentEnv=android

