name: Android Tests

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Enter Cucumber tag to run'
          required: true
          default: ""
          type: string
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CUCUMBER_TAG: ${{ github.event.inputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Appium + UiAutomator2 + default capabilities
      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
          echo '{
            "appium:adbExecTimeout": 120000,
            "appium:uiautomator2ServerInstallTimeout": 120000,
            "appium:uiautomator2ServerLaunchTimeout": 120000,
            "appium:appInstallTimeout": 120000}' > default-capabilities.json
          nohup appium --port 4723 --log-level info --default-capabilities "$(cat default-capabilities.json)" > appium.log 2>&1 &
          sleep 5
          appium driver list --installed

      - name: Run Android Emulator and Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-port: 5556
          target: default
          arch: x86_64
          profile: pixel_6
          script: |
            adb devices
            adb wait-for-device
            until adb shell getprop sys.boot_completed | grep -m 1 '1'; do sleep 5; done
            until adb shell pm list packages; do sleep 5; done
            echo "Emulator is fully booted!"
            adb shell input keyevent 82
            cat appium.log | tail -n 50
            mvn clean test \
            -Dspring.config.location=src/test/resources/application.yaml \
            -Duat.currentEnv=android \
            -Dcucumber.filter.tags="${CUCUMBER_TAG}"

      - name: Upload Appium Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: appium-logs
          path: appium.log
