name: Android Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Appium + UiAutomator2 + default capabilities
      - name: Setup Appium
        run: |
          npm install -g appium
          appium -v
          # Installer le driver Android
          appium driver install uiautomator2
          # Capabilities par défaut pour augmenter adbExecTimeout
          echo '{"adbExecTimeout": 60000}' > default-capabilities.json
          # Lancer Appium avec ces capabilities
          nohup appium --port 4723 --log-level info --default-capabilities "$(cat default-capabilities.json)" > appium.log 2>&1 &
          sleep 5
          appium driver list --installed

      - name: List all files recursively
        run: |
          echo "Listing all files in the project:"
          ls -R

      - name: Run Android Emulator and Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-port: 5556
          target: default
          arch: x86_64
          profile: pixel_6
          script: |
            adb devices
            adb wait-for-device
            adb shell getprop sys.boot_completed
            cat appium.log | tail -n 50
            mvn clean test -Dspring.config.location=src/test/resources/application.yaml -Duat.currentEnv=android
