name: iOS Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-ios:
    runs-on: macos-latest

    env:
     APP_PATH: /Users/runner/work/lacoste-mobile-app/lacoste-mobile-app/src/test/resources/iosApp/ios.app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: List available iOS simulators
      id: list-sim
      run: |
        echo "Available simulators:"
        xcrun simctl list devices available
        UDID=$(xcrun simctl list devices available | grep "iPhone 15 Pro (" | grep "iOS 17.5" | head -n 1 | awk -F '[()]' '{print $2}')
        if [ -z "$UDID" ]; then
          echo "No valid simulator found!"
          exit 1
        fi
        echo "SIM_UDID=$UDID" >> $GITHUB_ENV
        echo "Using simulator UDID: $UDID"

    - name: Boot simulator
      run: |
        xcrun simctl boot "$SIM_UDID" || echo "Simulator already booted"
        open -a Simulator

    - name: Start Appium
      run: |
        npm install -g appium
        appium --log-level info &

    - name: Run Maven tests
      run: |
        mvn clean test \
          -Dappium.deviceName="iPhone 15 Pro" \
          -Dappium.udid="$SIM_UDID" \
          -Dappium.platformVersion="17.5" \
          -Dappium.app="$APP_PATH" \
          -Dappium.automationName="XCUITest"

    - name: Shutdown simulator
      if: always()
      run: |
        xcrun simctl shutdown "$SIM_UDID"
