name: Android Appium Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install required SDK packages
      run: |
        sdkmanager "platform-tools" "emulator" "platforms;android-33" "system-images;android-33;google_apis;x86_64"

    - name: Create Android emulator
      run: |
        echo "no" | avdmanager create avd -n testAVD -k "system-images;android-33;google_apis;x86_64" --force
        emulator -list-avds

    - name: Start emulator
      run: |
        nohup emulator -avd testAVD -no-window -no-audio -no-snapshot -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell input keyevent 82
        sleep 20
        # Disable animations
        adb shell settings put global window_animation_scale 0.0
        adb shell settings put global transition_animation_scale 0.0
        adb shell settings put global animator_duration_scale 0.0

    - name: Start Appium server
      run: |
        npm install -g appium
        nohup appium --port 4723 --log-level info &
        sleep 5

    - name: Verify emulator
      run: adb devices

    - name: Run Maven tests
      run: mvn clean test -B

    - name: Kill emulator
      run: |
        adb -s emulator-5556 emu kill || echo "Emulator already stopped"
